#!/usr/bin/env php
<?php

use App\Console\ConsoleKernel;
use Framework\Console\ConsoleKernel as Kernel;
use Framework\Dispatcher\Dispatcher;
use Framework\Dispatcher\CliDispatcher;

include 'vendor/autoload.php';

app()->bind(Kernel::class, ConsoleKernel::class);
app()->singleton(Dispatcher::class, CliDispatcher::class);

try {
    app()->run(
        app()->make(Dispatcher::class)
    );
} catch (Error | Exception | Throwable $e) {
    if (_env('DEBUG')) {
        throw $e;
    }
    app()->handleError($e);
}
