#!/usr/bin/env php
<?php

use App\Console\ConsoleKernel;
use Framework\Application;
use Framework\Console\ConsoleKernel as Kernel;
use Framework\Dispatcher\Dispatcher;
use Framework\Dispatcher\CliDispatcher;

/* @var $application Application */

include 'boot.php';

$application->bind(Kernel::class, ConsoleKernel::class);
$application->singleton(Dispatcher::class, CliDispatcher::class);

$dispatcher = $application->make(Dispatcher::class);

try {
    $application->run($dispatcher);
} catch (Error | Exception | Throwable $e) {
    if (_env('DEBUG')) {
        throw $e;
    }
    $application->handleError($e);
}
