#!/usr/bin/php
<?php

global $argv;

include "php_deploy/vendor/autoload.php";

$env = isset($argv[1]) ? $argv[1] : die("Nincs megadva a környezet\n\n");

$deploy = php_deploy($env, __DIR__);

$deploy
    ->task('prepare:files', ['app', 'config', 'framework', 'public', 'resources', 'routes', 'boot.php', 'composer.json'])
    ->task('deploy:composer-install')
//    ->task('site:down')
    ->task('deploy:migrate')
    ->task('deploy:files')
    ->task('site:up')
    ->run();
